// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVvy73iIxflssFVEbd-0g7qFgfxpDbMLU',
    appId: '1:659936753588:web:54fb09c594258bc82624e1',
    messagingSenderId: '659936753588',
    projectId: 'thameen-36d3d',
    authDomain: 'thameen-36d3d.firebaseapp.com',
    storageBucket: 'thameen-36d3d.firebasestorage.app',
    measurementId: 'G-FC7PLVSYLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5uGuwVQFRSxaV36h5oDIuYL2CTk5anQ',
    appId: '1:659936753588:android:6fc2540fb725cabd2624e1',
    messagingSenderId: '659936753588',
    projectId: 'thameen-36d3d',
    storageBucket: 'thameen-36d3d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlXlHE7cvm1AwCO3O6OZlOOvvmiSkms_U',
    appId: '1:659936753588:ios:dc46fa3b34951a9f2624e1',
    messagingSenderId: '659936753588',
    projectId: 'thameen-36d3d',
    storageBucket: 'thameen-36d3d.firebasestorage.app',
    iosBundleId: 'com.example.thameen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlXlHE7cvm1AwCO3O6OZlOOvvmiSkms_U',
    appId: '1:659936753588:ios:dc46fa3b34951a9f2624e1',
    messagingSenderId: '659936753588',
    projectId: 'thameen-36d3d',
    storageBucket: 'thameen-36d3d.firebasestorage.app',
    iosBundleId: 'com.example.thameen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBVvy73iIxflssFVEbd-0g7qFgfxpDbMLU',
    appId: '1:659936753588:web:88475c8dad1b24b82624e1',
    messagingSenderId: '659936753588',
    projectId: 'thameen-36d3d',
    authDomain: 'thameen-36d3d.firebaseapp.com',
    storageBucket: 'thameen-36d3d.firebasestorage.app',
    measurementId: 'G-NL0QJQBHPW',
  );
}
